[[constraint]]
  branch = "master"
  name = "github.com/gosuri/uitable"

[[constraint]]
  name = "github.com/mitchellh/go-homedir"
  version = "1.1.0"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.3.2"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2.2.2"

[[constraint]]
  name = "github.com/Masterminds/semver"
  version = "3.0.0"

[[constraint]]
  name = "k8s.io/klog"
  version = "0.3.0"

[[constraint]]
  name = "github.com/mitchellh/go-spdx"
  version = "0.1.0"

[[override]]
  name = "golang.org/x/sys"
  branch = "master"

[prune]
  go-tests = true
  unused-packages = true

[[override]]
  name = "github.com/cpuguy83/go-md2man"
  version = "1.0.10"

[[override]]
  name = "github.com/russross/blackfriday"
  version = "1.5.2"

[[constraint]]
  name = "github.com/appsody/appsody-operator"
  version = "0.3.0"

[[override]]
  name = "k8s.io/apimachinery"
  revision = "27d36303b6556f377b4f34e64705fa9024a12b0c"

[[constraint]]
  branch = "master"
  name = "github.com/andrew-d/isbinary"
